# Generated by Django 5.2.7 on 2025-10-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_user_listing_listings_user_id_8788a1_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_user_id_8788a1_idx',
        ),
    ]
