# Generated by Django 5.2.7 on 2025-11-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_listings_user_id_8788a1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='watchlist_user_id_c64328_idx'), models.Index(fields=['listing'], name='watchlist_listing_209431_idx')],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
