# Generated by Django 5.2.8 on 2025-11-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
