# Generated by Django 5.2.7 on 2025-11-15 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid format",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "dorm",
                    models.CharField(
                        choices=[
                            ("founders_hall", "Founders Hall"),
                            ("hayden_hall", "Hayden Hall"),
                            ("weinstein_hall", "Weinstein Hall"),
                            ("brittany_hall", "Brittany Hall"),
                            ("rubin_hall", "Rubin Hall"),
                            ("third_north", "Third North"),
                            ("u_hall", "U-Hall"),
                            ("palladium", "Palladium"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="profiles_user_id_29277a_idx"),
                    models.Index(
                        fields=["username"], name="profiles_usernam_5dbb65_idx"
                    ),
                ],
            },
        ),
    ]
