# Generated by Django 5.2.7 on 2025-11-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_dorm_profile_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="location",
            new_name="dorm_location",
        ),
    ]
