# Generated by Django 5.2.7 on 2025-11-04 23:37

from django.db import migrations


def set_existing_users_verified(apps, schema_editor):
    """Set is_email_verified=True for all existing users"""
    User = apps.get_model("users", "User")
    User.objects.all().update(is_email_verified=True)


def reverse_set_existing_users_verified(apps, schema_editor):
    """Reverse migration - set is_email_verified=False"""
    User = apps.get_model("users", "User")
    User.objects.all().update(is_email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_email_verified"),
    ]

    operations = [
        migrations.RunPython(
            set_existing_users_verified, reverse_set_existing_users_verified
        ),
    ]
