# Generated by Django 5.2.7 on 2025-11-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_set_existing_users_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("attempts_count", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(auto_now=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "otp_attempts",
                "ordering": ["-last_attempt_at"],
                "indexes": [
                    models.Index(fields=["email"], name="otp_attempt_email_e05f00_idx"),
                    models.Index(
                        fields=["is_blocked", "blocked_until"],
                        name="otp_attempt_is_bloc_df423f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OTPAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate", "OTP Generated"),
                            ("verify", "OTP Verified"),
                            ("verify_failed", "OTP Verification Failed"),
                            ("block", "Account Blocked"),
                            ("unblock", "Account Unblocked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "otp_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["email", "timestamp"],
                        name="otp_audit_l_email_81d396_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="otp_audit_l_action_8d8fbf_idx",
                    ),
                    models.Index(
                        fields=["success", "timestamp"],
                        name="otp_audit_l_success_a4ce16_idx",
                    ),
                ],
            },
        ),
    ]
