# Generated by Django 5.2.8 on 2025-11-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_otpattempt_otpauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(
                db_column="user_id", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
    ]
